version: "3.9"

services:
  app:
    environment:
      SPRING_NEO4J_URI: bolt://host.docker.internal:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: test
      SPRING_URL: https://document-service-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
      JAVA_OPTS: -Xmx512m
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: maven-app
    volumes:
      - .:/app
    ports:
      - "8080:8080" # Порт для приложения
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
    external: false