app.ambassador-auth=true
app.feature.use-doc-service=true

server.tomcat.relaxed-query-chars=[,],{,}

spring.application.name=architect-graph
spring.neo4j.uri=bolt://neo4j-dev1.arch-code.cloud.vimpelcom.ru:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=securepassword
spring.services.graphviz.url=https://structurizr.vimpelcom.ru/graphviz
integration.authsso-server-url= https://ambassador-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru/rabbit-token
integration.product-server-url= https://fdm-products-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.mapper.accept-case-insensitive-properties=false

logging.level.io.opentelemetry.exporter.internal.http.HttpExporter=ERROR

server.tomcat.relaxed-query-chars=[,]
app.feature.use-doc-service=false
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.web.server.auto-time-requests=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true

queue.create-local-graph.name= create_local_graph
queue.build-local-graph.name= build_local_graph
queue.build-global-graph.name= build_global_graph
queue.create-global-graph.name= create_global_graph

otel.exporter.otlp.endpoint=http://otel-collector.opentelemetry:4318
otel.exporter.otlp.protocol=http/protobuf
otel.resource.attributes.host.name=@project.name@
otel.resource.attributes.service.namespace=@project.name@
otel.service.name=@project.name@
otel.instrumentation.log4j-appender.enabled=true
otel.logs.exporter=none
otel.sdk.disabled=true
