spring.application.name=architect-graph
spring.services.graphviz.url=https://structurizr.vimpelcom.ru/graphviz

logging.level.io.opentelemetry.exporter.internal.http.HttpExporter=ERROR

queue.create-local-graph.name= create_local_graph
queue.build-local-graph.name= build_local_graph
queue.create-global-graph.name= create_global_graph

otel.exporter.otlp.endpoint=http://otel-collector.opentelemetry:4318
otel.exporter.otlp.protocol=http/protobuf
otel.resource.attributes.host.name=@project.name@
otel.resource.attributes.service.namespace=@project.name@
otel.service.name=@project.name@
otel.instrumentation.log4j-appender.enabled=true
otel.logs.exporter=none
server.tomcat.relaxed-query-chars=[,]
