spring.application.name=architect-graph
spring.services.graphviz.url=https://structurizr.vimpelcom.ru/graphviz
queue.create-local-graph.name= create_local_graph
queue.create-global-graph.name= create_global_graph
