env:
  SPRING_NEO4J_URI: "vault:eafdmmart/data/dev/fdm#spring.neo4j.uri"
  SPRING_NEO4J_AUTHENTICATION_USERNAME: "vault:eafdmmart/data/dev/fdm#spring.neo4j.authentication.username"
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: "vault:eafdmmart/data/dev/fdm#spring.neo4j.authentication.password"
  SPRING_URL: "https://document-service-dev-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru/api/v1/documents/"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 100Mi
