env:
  SPRING_NEO4J_URI: "vault:eafdmmart/data/dev/fdm#spring.neo4j.uri"
  SPRING_NEO4J_AUTHENTICATION_USERNAME: "vault:eafdmmart/data/dev/fdm#spring.neo4j.authentication.username"
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: "vault:eafdmmart/data/dev/fdm#spring.neo4j.authentication.password"
  SPRING_REDIS_HOST: "redis-d1.database-dev-redis.cloud.vimpelcom.ru"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_PASSWORD: "vault:eafdmmart/data/dev/fdm#redispassword"
  INTEGRATION_AUTHSSO_SERVER_URL: "vault:eafdmmart/data/dev/ambassador#authsso"
  INTEGRATION_PRODUCT_SERVER_URL: "vault:eafdmmart/data/dev/fdm#productsserver"

podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'

resources:
  limits:
    cpu: 500m
    memory: 1500Mi
  requests:
    cpu: 100m
    memory: 300Mi
